access_log: False
app: "composition.webserver.hook:create_app"
factory: True
host: "0.0.0.0"
log_config: ".uvicorn.json"
port: 8000
reload: True
reload_excludes:
  - ".venv/*"
  - "*/__pycache__/*"
  - "*.pyc"
  - ".git"
server_header: False
