name: Entrypoint
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  linters:
    uses: ./.github/workflows/linters.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  system:
    uses: ./.github/workflows/system.yml
